# CMake generated Testfile for 
# Source directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/energy
# Build directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/cmake-cache/examples/energy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-energy-model-example "ns3.38-energy-model-example-default")
set_tests_properties(ctest-energy-model-example PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/examples/energy/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1770;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/energy/CMakeLists.txt;1;build_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/energy/CMakeLists.txt;0;")
add_test(ctest-energy-model-with-harvesting-example "ns3.38-energy-model-with-harvesting-example-default")
set_tests_properties(ctest-energy-model-with-harvesting-example PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/examples/energy/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1770;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/energy/CMakeLists.txt;13;build_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/energy/CMakeLists.txt;0;")
