# CMake generated Testfile for 
# Source directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples
# Build directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3.38-dumbbell-animation-default")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3.38-grid-animation-default")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3.38-star-animation-default")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3.38-colors-link-description-default")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3.38-resources-counters-default")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3.38-wireless-animation-default")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3.38-uan-animation-default")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/netanim/examples/CMakeLists.txt;0;")
