# CMake generated Testfile for 
# Source directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/udp-client-server
# Build directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/cmake-cache/examples/udp-client-server
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-udp-client-server "ns3.38-udp-client-server-default")
set_tests_properties(ctest-udp-client-server PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/examples/udp-client-server/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1770;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/udp-client-server/CMakeLists.txt;1;build_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/udp-client-server/CMakeLists.txt;0;")
add_test(ctest-udp-trace-client-server "ns3.38-udp-trace-client-server-default")
set_tests_properties(ctest-udp-trace-client-server PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/examples/udp-client-server/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1770;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/udp-client-server/CMakeLists.txt;10;build_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/examples/udp-client-server/CMakeLists.txt;0;")
