# CMake generated Testfile for 
# Source directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/olsr/examples
# Build directory: /Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/cmake-cache/src/olsr/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-olsr-hna "ns3.38-olsr-hna-default")
set_tests_properties(ctest-olsr-hna PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/olsr/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/olsr/examples/CMakeLists.txt;1;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/olsr/examples/CMakeLists.txt;0;")
add_test(ctest-simple-point-to-point-olsr "ns3.38-simple-point-to-point-olsr-default")
set_tests_properties(ctest-simple-point-to-point-olsr PROPERTIES  WORKING_DIRECTORY "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build/src/olsr/examples/" _BACKTRACE_TRIPLES "/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/olsr/examples/CMakeLists.txt;12;build_lib_example;/Users/stepa-kos/Desktop/practice/ns-3/ns-allinone-3.38/ns-3.38/src/olsr/examples/CMakeLists.txt;0;")
